# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'results.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ResultWindow(object):
    def setupUi(self, ResultWindow):
        ResultWindow.setObjectName("ResultWindow")
        ResultWindow.resize(551, 518)
        self.centralwidget = QtWidgets.QWidget(ResultWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.tableResult = QtWidgets.QTableWidget(self.centralwidget)
        self.tableResult.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableResult.setRowCount(0)
        self.tableResult.setColumnCount(0)
        self.tableResult.setObjectName("tableResult")
        self.tableResult.horizontalHeader().setStretchLastSection(True)
        self.gridLayout.addWidget(self.tableResult, 2, 1, 1, 1)
        self.tableParameters = QtWidgets.QTableWidget(self.centralwidget)
        self.tableParameters.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableParameters.setObjectName("tableParameters")
        self.tableParameters.setColumnCount(0)
        self.tableParameters.setRowCount(0)
        self.tableParameters.horizontalHeader().setStretchLastSection(True)
        self.gridLayout.addWidget(self.tableParameters, 2, 0, 1, 1)
        self.showCellParameters = QtWidgets.QPushButton(self.centralwidget)
        self.showCellParameters.setObjectName("showCellParameters")
        self.gridLayout.addWidget(self.showCellParameters, 1, 0, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        ResultWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ResultWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 551, 21))
        self.menubar.setObjectName("menubar")
        ResultWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ResultWindow)
        self.statusbar.setObjectName("statusbar")
        ResultWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ResultWindow)
        QtCore.QMetaObject.connectSlotsByName(ResultWindow)

    def retranslateUi(self, ResultWindow):
        _translate = QtCore.QCoreApplication.translate
        ResultWindow.setWindowTitle(_translate("ResultWindow", "Simulation Result"))
        self.showCellParameters.setText(_translate("ResultWindow", "Show Cell Parameters"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ResultWindow = QtWidgets.QMainWindow()
    ui = Ui_ResultWindow()
    ui.setupUi(ResultWindow)
    ResultWindow.show()
    sys.exit(app.exec_())
